### ISSUE TITLE
Metrics on overall behavior

### ISSUE THREAD

**Issue by artofnothingness** [artofnothingness/mppic#38]
It's ok that we somehow estimate effectiveness of this controller, but having some test scenarios with metrics, would help alot with estimating this more precisely

**Comment by SteveMacenski** [comment]
I think this would be quite challenging for macro-behaviors. Smaller things like smoothness and exact path following can be more exactly quantified, but system level behavior I think is very much qualitative (depending on the application and desired properties). 

With parameters tuned for exact path following, that could be a metric to use to tune the system with smoothness to get a nice behavior. But for the situation where we want the robot to deviate due to dynamic obstacles / creating more gentle less-rigid motions, that would be difficult to quantify the high level action, but there are some lower-level things like smoothness and accel/decel that might be in the same direction. I just don't think they are enough to encapsulate it fully

**Comment by SteveMacenski** [comment]
But in general:
- Smooth non-jerky motion
- Away from obstacles to a "reasonable" degree, don't skirt right up to them 
- "fluid" in some cases, rigid-exact-path-following in others
- Runtime performance of default parameters for execution frequency

**Comment by artofnothingness** [comment]
I don't see a way to do it fast in nearest perspective
