### ISSUE TITLE
Optimize path align critic & obstacles critic

### ISSUE THREAD

**Issue by artofnothingness** [artofnothingness/mppic#45]
Just some thoughts came up
Now ref critic is about O(BTP) (batch_size x time_step x path_len)

I start doubting that we really need critic that penalize exact distance between current batch point and path line segment (between path points)

Probably local goal critic with some offset plus simple goal critic would be enough. 
Plus consider local goal as the farthest nearest goal to batches last point (now we searching for farthest nearest goal to all batches points)

**Comment by SteveMacenski** [comment]
Certainly, but it can also be improved by:

As you're marching through the path and the closest path point (`pi`) to trajectory point (`ti`) is found, then in the next iteration you can start at `pi` for finding the closest point to `ti+1` rather than restarting from `0`. That would restrict your search by a full dimension by only iterating through the entire path 1 time. 

The only odd edge case that would need to be considered is when you're reversing, temporarily to get around an obstacle then going back to forward, that the little reversing patch would need to mach in reverse on the path (e.g. `pi-N`). But if you were fully reversing, then it would work fine, its only where there's a discrete change in direction which you could detect.

Another option to reduce the search space in the path used to be at most `max velocity * max time considered` away from the robot in either direction so that you're working with the smallest subset of the path possible to iterate over. Rather than `reference_segments_count` as the size of the path, you could find the first point the furthest away as any trajectory point being considered and simply ignore anything after that for matching up. E.g. max(trajectory_points), find the index in the path that matches to that distance away, only iterate to there. 

How dense are the generated trajectory points? I believe `dt` away, correct? If the robot's max speed is `0.5m/s` and the dt is `0.05` for 20hz control, then the distance between them is ~2.5cm. Most paths are going to be giving you results at the costmaps resolution, typically 5-10cm. So what you could do is check the distance between the last path point considered and skip some so that you only check for trajectory points that are at least 1 costmap cell away from the last one considered. For this example, that would reduce the number of checks by 50%. I think checking all points is overkill, even ignoring the costmap resolution / speed argument, simply having a parameter for modulating the number to check would be an easy way to reduce by double-digit percentages without any real impact on the functionality. For instance, only check every 3rd trajectory point. 

Using parallel processing is also something possible, even without a GPU we could spin up 2-3 threads to speed it up.  

I could probably come up with a couple more optimization points, but I think its worth trying to see if a single-point check is enough. I think that's what you used to have as the approximate reference path critic? Maybe worth reviving that and testing to see how well it works / behavioral changes.  I don't think it would be bad to have both around, especially if we think we can improve the performance of this one sufficiently.

**Comment by artofnothingness** [comment]
> How dense are the generated trajectory points? I believe dt away, correct? I

yeah

> How dense are the generated trajectory points? I believe dt away, correct? If the robot's max speed is 0.5m/s and the dt is 0.05 for 20hz control, then the distance between them is ~2.5cm. Most paths are going to be giving you results at the costmaps resolution, typically 5-10cm. So what you could do is check the distance between the last path point considered and skip some so that you only check for trajectory points that are at least 1 costmap cell away from the last one considered. For this example, that would reduce the number of checks by 50%. I think checking all points is overkill, even ignoring the costmap resolution / speed argument, simply having a parameter for modulating the number to check would be an easy way to reduce by double-digit percentages without any real impact on the functionality. For instance, only check every 3rd trajectory point> .

That's a good idea

> Using parallel processing is also something possible, even without a GPU we could spin up 2-3 threads to speed it up.

xtensor could work with with openmp and tbb somehow

> but I think its worth trying to see if a single-point check is enough. I think that's what you used to have as the approximate reference path critic

In my older tests that led to behavior when trajectory points stick to path points, and not trajectory itself (some trajectory points was pulling back, some pulling forward). Reference critic must just align trajectory to reference path, not pull it back/forward

**Comment by artofnothingness** [comment]
> Another option to reduce the search space in the path used to be at most max velocity * max time considered away from the robot in either direction so that you're working with the smallest subset of the path possible to iterate over. Rather than reference_segments_count as the size of the path, you could find the first point the furthest away as any trajectory point being considered and simply ignore anything after that for matching up. E.g. max(trajectory_points), find the index in the path that matches to that distance away, only iterate to there.

You mean max speed set by constraints, or max speed from state ? 
If set by constraints, we could prune the path in path handler

**Comment by SteveMacenski** [comment]
> xtensor could work with with openmp and tbb somehow

I did some googling from another thread we were having, Eigen actually has built in OpenCL/Cuda support for tensors, as well as multithreading support for CPUs. http://eigen.tuxfamily.org/index.php?title=Tensor_support

> In my older tests that led to behavior when trajectory points stick to path points, and not trajectory itself (some trajectory points was pulling back, some pulling forward). Reference critic must just align trajectory to reference path, not pull it back/forward

Yeah, and i was thinking too if the reference path critic doesn't have some kind of 'integrated' value, then the wobbling for path tracking would be worse. It needs some kind of integrated area between them / summed distance metric over many points to help the optimizer converge the best.

 > You mean max speed set by constraints, or max speed from state ? If set by constraints, we could prune the path in path handler

I mean (more refined, not exactly what I said before) by the current set of trajectories. If you have `N` trajectories, find the furthest distance away any of them forward/backward from the robot pose and then prune the global path (or just store the `start_i` and `end_i`'s for the for loop rather than literally pruning) to use only that range. That way you're reducing the range of the global path plan you need to iterate over to only the extents that there are any trajectory points generated from the controller to care about.

Before I was talking about speeds, but who cares about that, we actually do just have the positions in each of the trajectories, no need to integrate velocities or guesstimate.

**Comment by artofnothingness** [comment]
> Before I was talking about speeds, but who cares about that, we actually do just have the positions in each of the trajectories, no need to integrate velocities or guesstimate

We actually do have velocities for each point

**Comment by mkolodziejczyk-piap** [comment]
I haven't finished all the porting yet, but my GPU approach is

1. I'm keeping trajectories and segments in the following tensors (arrayfire convention):

trajectories.dims= (2, trajectories_count, trajectories_points_count)

segments.dims = (2, reference_segments_count)

2. Then I tile both to have dim

(2, trajectories_count * trajectories_points_count * reference_segments_count)

3. Then I do one big parallel for on the last dimension

**Comment by artofnothingness** [comment]
@mkolodziejczyk-piap 
I did almost the same for reference critic, using standard parallel for, but it didn't give me a lot

**Comment by SteveMacenski** [comment]
I don't think we need them though for the reference critic. See diagram

![unnamed](https://user-images.githubusercontent.com/14944147/167508680-f62ab885-f290-4c71-a61c-8b1e3e8a47e4.jpg)

If we have path of length 10, but a trajectory of length 2, we can find the point on path, `p_l` which is 2 away from the trajectory starting point and then only use `0 -> p_l` to evaluate against all trajectory points, since we know anything past path length point L = 2.0 is going to be reasonably out of bounds of interest. That reduces the space of path points you need to consider if your nested loops from `0 -> path.size()` to `0 -> p_l`. This should be based on integrated distance, rather than L2 distance to make sure of that. 

That paired with only considering every 2nd or 3rd trajectory point should give you a ~2x speed up.

**Comment by mkolodziejczyk-piap** [comment]
> I did some googling from another thread we were having, Eigen actually has built in OpenCL/Cuda support for tensors, as well as multithreading support for CPUs. http://eigen.tuxfamily.org/index.php?title=Tensor_support

AFAIR this was a project of one of Tensorflow developers and it was dropped when TF was started (TF still got some Eigen dependencies)

**Comment by mkolodziejczyk-piap** [comment]
> @mkolodziejczyk-piap I did almost the same for reference critic, using standard parallel for, but it didn't give me a lot

Will see but number of GPU threads should do the job

**Comment by artofnothingness** [comment]
> I don't think we need them though for the reference critic. See diagram

Agree

> If we have path of length 10, but a trajectory of length 2, we can find the point on path, p_l which is 2 away from the trajectory starting point and then only use 0 -> p_l to evaluate against all trajectory points, since we know anything past path length point L = 2.0 is going to be reasonably out of bounds of interest. That reduces the space of path points you need to consider if your nested loops from 0 -> path.size() to 0 -> p_l. This should be based on integrated distance, rather than L2 distance to make sure of that. That paired with only considering every 2nd or 3rd trajectory point should give you a ~2x speed up.

I'm not sure i get the idea right 

![image](https://user-images.githubusercontent.com/48126993/167511226-8bdc03b2-0e9a-4a3e-b278-3018dd82dfb9.png)
We have trajectory 1,2,3, Path,
If we use for trajectory two, nearest to path point from trajectory one, it would be wrong

**Comment by artofnothingness** [comment]
> If we have path of length 10, but a trajectory of length 2, we can find the point on path, p_l which is 2 away from the trajectory starting point and then only use 0 -> p_l to evaluate against all trajectory points, since we know anything past path length point L = 2.0 is going to be reasonably out of bounds of interest. That reduces the space of path points you need to consider if your nested loops from 0 -> path.size() to 0 -> p_l. This should be based on integrated distance, rather than L2 distance to make sure of that.

Hm.. That seems reasonable

**Comment by artofnothingness** [comment]
> Will see but number of GPU threads should do the job

Yeah, i did this on cpu. Quite exciting

**Comment by SteveMacenski** [comment]
Is there more work  to be done here or does #53 cover it?

**Comment by artofnothingness** [comment]
Optimization that you propose must go after #53
