### ISSUE TITLE
Desired speed Critic

### ISSUE THREAD

**Issue by artofnothingness** [artofnothingness/mppic#50]
Penalize for difference between trajectories velocities (mean?), and maximum velocity

**Comment by SteveMacenski** [comment]
I would not over complicate things unless we noticed that in steady state navigation the robot was selectively not going as fast as it could be. From the tuning we had before, I tested it and it was right at the top range so I think it was OK. But I do recall when we had more 'restrained' tuning to path following, it did not achieve the max speed - so perhaps that could be of interest. 

I'd be concerned with jerky motion if we did this and wasn't balanced with a smoothing critic https://github.com/artofnothingness/mppic/issues/41 or kinematic feasibility critic, especially related to backing out maneuvers or in scenes with dynamic agents or lots of confined spaces if its trying to barrel ahead at max speed. Then we're talking about maximizing speed, minimizing smoothness, possibly adding more critics for slowing down in particular situations (like heavy turns, etc), that's starting to make the optimization space much less convex before we even add in the goal / path / task critics. Not saying that we might not eventually need to do something like this -- but I'd wait for it to be evidence based (e.g. there's a problem). Is there a problem with this yet? 

Right now, we have no feasibility items (e.g. if max acceleration would not allow us to go from 2 to 2.5 m/s in 1 timestep) so if we start going down this direction we'll have to specifically model kinematic constraints at the timestep level as well to make sure the optimization problem isn't going to get to the extremes more quickly than physically possible. At the moment, we're hand waving that away since we're not encouraging it and we're moving relatively speaking slowly. 

The fact that the  controller's task is to drive toward the goal / path makes the critics already naturally want to go forward. After N iterations, it would be at full speed unless some other critics were restricting speed because its cost function was more important (e.g. being super close to the path for exact following outweighed drive to goal desire).

We may eventually need to go this direction, but it opens a whole can of worms

**Comment by artofnothingness** [comment]
I would add that in previous parameters there was huge goal cost, which made problems with obstacles and sometimes led to stucking in front of obstacles (if goal right behind the obstacle)

Generally i agree

**Comment by SteveMacenski** [comment]
That's a good point. I think this can be rolled into the discussion in #41 though, I think these are in the same theme and all intrinsically tied together.

**Comment by SteveMacenski** [comment]
From #53 I think we found that the path follow critic incentives going at speed. Do we still need a separate critic?

**Comment by artofnothingness** [comment]
Probably path follow will be enough
